---
# Project information
site_name: CPP Lab Guide
repo_name: cpp-lln-lab/CPP_LabGuide
repo_url: https://github.com/cpp-lln-lab/CPP_LabGuide
# docs_dir: alternative_path # docs/ is the default folder
copyright: MIT

# This will use Material them
theme:
  name: material
  language: en
  palette:
    primary: light blue
    accent: light blue
  features:
  - navigation.expand

docs_dir: doc

# Pages
nav:
- Welcome and FAQ: index.md
- Contributing: contributing.md

# list of extension
markdown_extensions:
- admonition
- pymdownx.details
- toc:
    anchorlink: true
    permalink: '#'
- pymdownx.tasklist:
    custom_checkbox: true

plugins:
- include-markdown
